# Generated by Django 3.0.3 on 2020-02-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200211_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=10)),
                ('article_month', models.CharField(max_length=15)),
                ('article_year', models.IntegerField()),
                ('article_author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
        migrations.DeleteModel(
            name='dreamreal',
        ),
        migrations.DeleteModel(
            name='Online',
        ),
    ]
