# Generated by Django 3.0.3 on 2020-02-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200212_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_year',
            field=models.CharField(max_length=10),
        ),
    ]
