# Generated by Django 3.0.3 on 2020-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20200218_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=500)),
                ('poll_count_yes', models.IntegerField()),
                ('poll_count_no', models.IntegerField()),
            ],
            options={
                'db_table': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserProfiles',
            },
        ),
        migrations.DeleteModel(
            name='article',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TempModel',
        ),
        migrations.AddField(
            model_name='poll',
            name='Users',
            field=models.ManyToManyField(to='first_app.UserProfile'),
        ),
    ]
