# Generated by Django 3.0.3 on 2020-02-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20200218_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(max_length=100),
        ),
    ]
