# Generated by Django 3.0.3 on 2020-02-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_poll_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
